using LVK.Bootstrapping;

using Microsoft.EntityFrameworkCore;

namespace GameTools.Database;

internal class ModuleInitializer : IModuleInitializer
{
    private readonly IDbContextFactory<GameToolsDbContext> _dbContextFactory;

    public ModuleInitializer(IDbContextFactory<GameToolsDbContext> dbContextFactory)
    {
        _dbContextFactory = dbContextFactory ?? throw new ArgumentNullException(nameof(dbContextFactory));
    }

    public async Task InitializeAsync(CancellationToken cancellationToken)
    {
        await using GameToolsDbContext dbContext = await _dbContextFactory.CreateDbContextAsync(cancellationToken);
        await dbContext.Database.MigrateAsync(cancellationToken);
        await FillGalaxiesAsync(dbContext);
    }

    private async Task FillGalaxiesAsync(GameToolsDbContext dbContext)
    {
        var galaxies = new List<NoMansSkyGalaxy>
        {
            new() { Id = 1, Name = "Euclid", Type = "Normal" },
            new() { Id = 2, Name = "Hilbert Dimension", Type = "Normal" },
            new() { Id = 3, Name = "Calypso", Type = "Harsh" },
            new() { Id = 4, Name = "Hesperius Dimension", Type = "Normal" },
            new() { Id = 5, Name = "Hyades", Type = "Normal" },
            new() { Id = 6, Name = "Ickjamatew", Type = "Normal" },
            new() { Id = 7, Name = "Budullangr", Type = "Empty" },
            new() { Id = 8, Name = "Kikolgallr", Type = "Normal" },
            new() { Id = 9, Name = "Eltiensleen", Type = "Normal" },
            new() { Id = 10, Name = "Eissentam", Type = "Lush" },
            new() { Id = 11, Name = "Elkupalos", Type = "Normal" },
            new() { Id = 12, Name = "Aptarkaba", Type = "Empty" },
            new() { Id = 13, Name = "Ontiniangp", Type = "Normal" },
            new() { Id = 14, Name = "Odiwagiri", Type = "Normal" },
            new() { Id = 15, Name = "Ogtialabi", Type = "Harsh" },
            new() { Id = 16, Name = "Muhacksonto", Type = "Normal" },
            new() { Id = 17, Name = "Hitonskyer", Type = "Normal" },
            new() { Id = 18, Name = "Rerasmutul", Type = "Normal" },
            new() { Id = 19, Name = "Isdoraijung", Type = "Lush" },
            new() { Id = 20, Name = "Doctinawyra", Type = "Normal" },
            new() { Id = 21, Name = "Loychazinq", Type = "Normal" },
            new() { Id = 22, Name = "Zukasizawa", Type = "Normal" },
            new() { Id = 23, Name = "Ekwathore", Type = "Harsh" },
            new() { Id = 24, Name = "Yeberhahne", Type = "Normal" },
            new() { Id = 25, Name = "Twerbetek", Type = "Normal" },
            new() { Id = 26, Name = "Sivarates", Type = "Normal" },
            new() { Id = 27, Name = "Eajerandal", Type = "Empty" },
            new() { Id = 28, Name = "Aldukesci", Type = "Normal" },
            new() { Id = 29, Name = "Wotyarogii", Type = "Normal" },
            new() { Id = 30, Name = "Sudzerbal", Type = "Lush" },
            new() { Id = 31, Name = "Maupenzhay", Type = "Normal" },
            new() { Id = 32, Name = "Sugueziume", Type = "Empty" },
            new() { Id = 33, Name = "Brogoweldian", Type = "Normal" },
            new() { Id = 34, Name = "Ehbogdenbu", Type = "Normal" },
            new() { Id = 35, Name = "Ijsenufryos", Type = "Harsh" },
            new() { Id = 36, Name = "Nipikulha", Type = "Normal" },
            new() { Id = 37, Name = "Autsurabin", Type = "Normal" },
            new() { Id = 38, Name = "Lusontrygiamh", Type = "Normal" },
            new() { Id = 39, Name = "Rewmanawa", Type = "Lush" },
            new() { Id = 40, Name = "Ethiophodhe", Type = "Normal" },
            new() { Id = 41, Name = "Urastrykle", Type = "Normal" },
            new() { Id = 42, Name = "Xobeurindj", Type = "Normal" },
            new() { Id = 43, Name = "Oniijialdu", Type = "Harsh" },
            new() { Id = 44, Name = "Wucetosucc", Type = "Normal" },
            new() { Id = 45, Name = "Ebyeloof", Type = "Normal" },
            new() { Id = 46, Name = "Odyavanta", Type = "Normal" },
            new() { Id = 47, Name = "Milekistri", Type = "Empty" },
            new() { Id = 48, Name = "Waferganh", Type = "Normal" },
            new() { Id = 49, Name = "Agnusopwit", Type = "Normal" },
            new() { Id = 50, Name = "Teyaypilny", Type = "Lush" },
            new() { Id = 51, Name = "Zalienkosm", Type = "Normal" },
            new() { Id = 52, Name = "Ladgudiraf", Type = "Empty" },
            new() { Id = 53, Name = "Mushonponte", Type = "Normal" },
            new() { Id = 54, Name = "Amsentisz", Type = "Normal" },
            new() { Id = 55, Name = "Fladiselm", Type = "Harsh" },
            new() { Id = 56, Name = "Laanawemb", Type = "Normal" },
            new() { Id = 57, Name = "Ilkerloor", Type = "Normal" },
            new() { Id = 58, Name = "Davanossi", Type = "Normal" },
            new() { Id = 59, Name = "Ploehrliou", Type = "Lush" },
            new() { Id = 60, Name = "Corpinyaya", Type = "Normal" },
            new() { Id = 61, Name = "Leckandmeram", Type = "Normal" },
            new() { Id = 62, Name = "Quulngais", Type = "Normal" },
            new() { Id = 63, Name = "Nokokipsechl", Type = "Harsh" },
            new() { Id = 64, Name = "Rinblodesa", Type = "Normal" },
            new() { Id = 65, Name = "Loydporpen", Type = "Normal" },
            new() { Id = 66, Name = "Ibtrevskip", Type = "Normal" },
            new() { Id = 67, Name = "Elkowaldb", Type = "Empty" },
            new() { Id = 68, Name = "Heholhofsko", Type = "Normal" },
            new() { Id = 69, Name = "Yebrilowisod", Type = "Normal" },
            new() { Id = 70, Name = "Husalvangewi", Type = "Lush" },
            new() { Id = 71, Name = "Ovna'uesed", Type = "Normal" },
            new() { Id = 72, Name = "Bahibusey", Type = "Empty" },
            new() { Id = 73, Name = "Nuybeliaure", Type = "Normal" },
            new() { Id = 74, Name = "Doshawchuc", Type = "Normal" },
            new() { Id = 75, Name = "Ruckinarkh", Type = "Harsh" },
            new() { Id = 76, Name = "Thorettac", Type = "Normal" },
            new() { Id = 77, Name = "Nuponoparau", Type = "Normal" },
            new() { Id = 78, Name = "Moglaschil", Type = "Normal" },
            new() { Id = 79, Name = "Uiweupose", Type = "Lush" },
            new() { Id = 80, Name = "Nasmilete", Type = "Normal" },
            new() { Id = 81, Name = "Ekdaluskin", Type = "Normal" },
            new() { Id = 82, Name = "Hakapanasy", Type = "Normal" },
            new() { Id = 83, Name = "Dimonimba", Type = "Harsh" },
            new() { Id = 84, Name = "Cajaccari", Type = "Normal" },
            new() { Id = 85, Name = "Olonerovo", Type = "Normal" },
            new() { Id = 86, Name = "Umlanswick", Type = "Normal" },
            new() { Id = 87, Name = "Henayliszm", Type = "Empty" },
            new() { Id = 88, Name = "Utzenmate", Type = "Normal" },
            new() { Id = 89, Name = "Umirpaiya", Type = "Normal" },
            new() { Id = 90, Name = "Paholiang", Type = "Lush" },
            new() { Id = 91, Name = "Iaereznika", Type = "Normal" },
            new() { Id = 92, Name = "Yudukagath", Type = "Empty" },
            new() { Id = 93, Name = "Boealalosnj", Type = "Normal" },
            new() { Id = 94, Name = "Yaevarcko", Type = "Normal" },
            new() { Id = 95, Name = "Coellosipp", Type = "Harsh" },
            new() { Id = 96, Name = "Wayndohalou", Type = "Normal" },
            new() { Id = 97, Name = "Smoduraykl", Type = "Normal" },
            new() { Id = 98, Name = "Apmaneessu", Type = "Normal" },
            new() { Id = 99, Name = "Hicanpaav", Type = "Lush" },
            new() { Id = 100, Name = "Akvasanta", Type = "Normal" },
            new() { Id = 101, Name = "Tuychelisaor", Type = "Normal" },
            new() { Id = 102, Name = "Rivskimbe", Type = "Normal" },
            new() { Id = 103, Name = "Daksanquix", Type = "Harsh" },
            new() { Id = 104, Name = "Kissonlin", Type = "Normal" },
            new() { Id = 105, Name = "Aediabiel", Type = "Normal" },
            new() { Id = 106, Name = "Ulosaginyik", Type = "Normal" },
            new() { Id = 107, Name = "Roclaytonycar", Type = "Empty" },
            new() { Id = 108, Name = "Kichiaroa", Type = "Normal" },
            new() { Id = 109, Name = "Irceauffey", Type = "Normal" },
            new() { Id = 110, Name = "Nudquathsenfe", Type = "Lush" },
            new() { Id = 111, Name = "Getaizakaal", Type = "Normal" },
            new() { Id = 112, Name = "Hansolmien", Type = "Empty" },
            new() { Id = 113, Name = "Bloytisagra", Type = "Normal" },
            new() { Id = 114, Name = "Ladsenlay", Type = "Normal" },
            new() { Id = 115, Name = "Luyugoslasr", Type = "Harsh" },
            new() { Id = 116, Name = "Ubredhatk", Type = "Normal" },
            new() { Id = 117, Name = "Cidoniana", Type = "Normal" },
            new() { Id = 118, Name = "Jasinessa", Type = "Normal" },
            new() { Id = 119, Name = "Torweierf", Type = "Lush" },
            new() { Id = 120, Name = "Saffneckm", Type = "Normal" },
            new() { Id = 121, Name = "Thnistner", Type = "Normal" },
            new() { Id = 122, Name = "Dotusingg", Type = "Normal" },
            new() { Id = 123, Name = "Luleukous", Type = "Harsh" },
            new() { Id = 124, Name = "Jelmandan", Type = "Normal" },
            new() { Id = 125, Name = "Otimanaso", Type = "Normal" },
            new() { Id = 126, Name = "Enjaxusanto", Type = "Normal" },
            new() { Id = 127, Name = "Sezviktorew", Type = "Empty" },
            new() { Id = 128, Name = "Zikehpm", Type = "Normal" },
            new() { Id = 129, Name = "Bephembah", Type = "Normal" },
            new() { Id = 130, Name = "Broomerrai", Type = "Lush" },
            new() { Id = 131, Name = "Meximicka", Type = "Normal" },
            new() { Id = 132, Name = "Venessika", Type = "Empty" },
            new() { Id = 133, Name = "Gaiteseling", Type = "Normal" },
            new() { Id = 134, Name = "Zosakasiro", Type = "Normal" },
            new() { Id = 135, Name = "Drajayanes", Type = "Harsh" },
            new() { Id = 136, Name = "Ooibekuar", Type = "Normal" },
            new() { Id = 137, Name = "Urckiansi", Type = "Normal" },
            new() { Id = 138, Name = "Dozivadido", Type = "Normal" },
            new() { Id = 139, Name = "Emiekereks", Type = "Lush" },
            new() { Id = 140, Name = "Meykinunukur", Type = "Normal" },
            new() { Id = 141, Name = "Kimycuristh", Type = "Normal" },
            new() { Id = 142, Name = "Roansfien", Type = "Normal" },
            new() { Id = 143, Name = "Isgarmeso", Type = "Harsh" },
            new() { Id = 144, Name = "Daitibeli", Type = "Normal" },
            new() { Id = 145, Name = "Gucuttarik", Type = "Normal" },
            new() { Id = 146, Name = "Enlaythie", Type = "Normal" },
            new() { Id = 147, Name = "Drewweste", Type = "Empty" },
            new() { Id = 148, Name = "Akbulkabi", Type = "Normal" },
            new() { Id = 149, Name = "Homskiw", Type = "Normal" },
            new() { Id = 150, Name = "Zavainlani", Type = "Lush" },
            new() { Id = 151, Name = "Jewijkmas", Type = "Normal" },
            new() { Id = 152, Name = "Itlhotagra", Type = "Empty" },
            new() { Id = 153, Name = "Podalicess", Type = "Normal" },
            new() { Id = 154, Name = "Hiviusauer", Type = "Normal" },
            new() { Id = 155, Name = "Halsebenk", Type = "Harsh" },
            new() { Id = 156, Name = "Puikitoac", Type = "Normal" },
            new() { Id = 157, Name = "Gaybakuaria", Type = "Normal" },
            new() { Id = 158, Name = "Grbodubhe", Type = "Normal" },
            new() { Id = 159, Name = "Rycempler", Type = "Lush" },
            new() { Id = 160, Name = "Indjalala", Type = "Normal" },
            new() { Id = 161, Name = "Fontenikk", Type = "Normal" },
            new() { Id = 162, Name = "Pasycihelwhee", Type = "Normal" },
            new() { Id = 163, Name = "Ikbaksmit", Type = "Harsh" },
            new() { Id = 164, Name = "Telicianses", Type = "Normal" },
            new() { Id = 165, Name = "Oyleyzhan", Type = "Normal" },
            new() { Id = 166, Name = "Uagerosat", Type = "Normal" },
            new() { Id = 167, Name = "Impoxectin", Type = "Empty" },
            new() { Id = 168, Name = "Twoodmand", Type = "Normal" },
            new() { Id = 169, Name = "Hilfsesorbs", Type = "Normal" },
            new() { Id = 170, Name = "Ezdaranit", Type = "Lush" },
            new() { Id = 171, Name = "Wiensanshe", Type = "Normal" },
            new() { Id = 172, Name = "Ewheelonc", Type = "Empty" },
            new() { Id = 173, Name = "Litzmantufa", Type = "Normal" },
            new() { Id = 174, Name = "Emarmatosi", Type = "Normal" },
            new() { Id = 175, Name = "Mufimbomacvi", Type = "Harsh" },
            new() { Id = 176, Name = "Wongquarum", Type = "Normal" },
            new() { Id = 177, Name = "Hapirajua", Type = "Normal" },
            new() { Id = 178, Name = "Igbinduina", Type = "Normal" },
            new() { Id = 179, Name = "Wepaitvas", Type = "Lush" },
            new() { Id = 180, Name = "Sthatigudi", Type = "Normal" },
            new() { Id = 181, Name = "Yekathsebehn", Type = "Normal" },
            new() { Id = 182, Name = "Ebedeagurst", Type = "Normal" },
            new() { Id = 183, Name = "Nolisonia", Type = "Harsh" },
            new() { Id = 184, Name = "Ulexovitab", Type = "Normal" },
            new() { Id = 185, Name = "Iodhinxois", Type = "Normal" },
            new() { Id = 186, Name = "Irroswitzs", Type = "Normal" },
            new() { Id = 187, Name = "Bifredait", Type = "Empty" },
            new() { Id = 188, Name = "Beiraghedwe", Type = "Normal" },
            new() { Id = 189, Name = "Yeonatlak", Type = "Normal" },
            new() { Id = 190, Name = "Cugnatachh", Type = "Lush" },
            new() { Id = 191, Name = "Nozoryenki", Type = "Normal" },
            new() { Id = 192, Name = "Ebralduri", Type = "Empty" },
            new() { Id = 193, Name = "Evcickcandj", Type = "Normal" },
            new() { Id = 194, Name = "Ziybosswin", Type = "Normal" },
            new() { Id = 195, Name = "Heperclait", Type = "Harsh" },
            new() { Id = 196, Name = "Sugiuniam", Type = "Normal" },
            new() { Id = 197, Name = "Aaseertush", Type = "Normal" },
            new() { Id = 198, Name = "Uglyestemaa", Type = "Normal" },
            new() { Id = 199, Name = "Horeroedsh", Type = "Lush" },
            new() { Id = 200, Name = "Drundemiso", Type = "Normal" },
            new() { Id = 201, Name = "Ityanianat", Type = "Normal" },
            new() { Id = 202, Name = "Purneyrine", Type = "Normal" },
            new() { Id = 203, Name = "Dokiessmat", Type = "Harsh" },
            new() { Id = 204, Name = "Nupiacheh", Type = "Normal" },
            new() { Id = 205, Name = "Dihewsonj", Type = "Normal" },
            new() { Id = 206, Name = "Rudrailhik", Type = "Normal" },
            new() { Id = 207, Name = "Tweretnort", Type = "Empty" },
            new() { Id = 208, Name = "Snatreetze", Type = "Normal" },
            new() { Id = 209, Name = "Iwundaracos", Type = "Normal" },
            new() { Id = 210, Name = "Digarlewena", Type = "Lush" },
            new() { Id = 211, Name = "Erquagsta", Type = "Normal" },
            new() { Id = 212, Name = "Logovoloin", Type = "Empty" },
            new() { Id = 213, Name = "Boyaghosganh", Type = "Normal" },
            new() { Id = 214, Name = "Kuolungau", Type = "Normal" },
            new() { Id = 215, Name = "Pehneldept", Type = "Harsh" },
            new() { Id = 216, Name = "Yevettiiqidcon", Type = "Normal" },
            new() { Id = 217, Name = "Sahliacabru", Type = "Normal" },
            new() { Id = 218, Name = "Noggalterpor", Type = "Normal" },
            new() { Id = 219, Name = "Chmageaki", Type = "Lush" },
            new() { Id = 220, Name = "Veticueca", Type = "Normal" },
            new() { Id = 221, Name = "Vittesbursul", Type = "Normal" },
            new() { Id = 222, Name = "Nootanore", Type = "Normal" },
            new() { Id = 223, Name = "Innebdjerah", Type = "Harsh" },
            new() { Id = 224, Name = "Kisvarcini", Type = "Normal" },
            new() { Id = 225, Name = "Cuzcogipper", Type = "Normal" },
            new() { Id = 226, Name = "Pamanhermonsu", Type = "Normal" },
            new() { Id = 227, Name = "Brotoghek", Type = "Empty" },
            new() { Id = 228, Name = "Mibittara", Type = "Normal" },
            new() { Id = 229, Name = "Huruahili", Type = "Normal" },
            new() { Id = 230, Name = "Raldwicarn", Type = "Lush" },
            new() { Id = 231, Name = "Ezdartlic", Type = "Normal" },
            new() { Id = 232, Name = "Badesclema", Type = "Empty" },
            new() { Id = 233, Name = "Isenkeyan", Type = "Normal" },
            new() { Id = 234, Name = "Iadoitesu", Type = "Normal" },
            new() { Id = 235, Name = "Yagrovoisi", Type = "Harsh" },
            new() { Id = 236, Name = "Ewcomechio", Type = "Normal" },
            new() { Id = 237, Name = "Inunnunnoda", Type = "Normal" },
            new() { Id = 238, Name = "Dischiutun", Type = "Normal" },
            new() { Id = 239, Name = "Yuwarugha", Type = "Lush" },
            new() { Id = 240, Name = "Ialmendra", Type = "Normal" },
            new() { Id = 241, Name = "Reponudrle", Type = "Normal" },
            new() { Id = 242, Name = "Rinjanagrbo", Type = "Normal" },
            new() { Id = 243, Name = "Zeziceloh", Type = "Harsh" },
            new() { Id = 244, Name = "Oeileutasc", Type = "Normal" },
            new() { Id = 245, Name = "Zicniijinis", Type = "Normal" },
            new() { Id = 246, Name = "Dugnowarilda", Type = "Normal" },
            new() { Id = 247, Name = "Neuxoisan", Type = "Empty" },
            new() { Id = 248, Name = "Ilmenhorn", Type = "Normal" },
            new() { Id = 249, Name = "Rukwatsuku", Type = "Normal" },
            new() { Id = 250, Name = "Nepitzaspru", Type = "Lush" },
            new() { Id = 251, Name = "Chcehoemig", Type = "Normal" },
            new() { Id = 252, Name = "Haffneyrin", Type = "Empty" },
            new() { Id = 253, Name = "Uliciawai", Type = "Normal" },
            new() { Id = 254, Name = "Tuhgrespod", Type = "Normal" },
            new() { Id = 255, Name = "Iousongola", Type = "Harsh" },
            new() { Id = 256, Name = "Odyalutai", Type = "Normal" },
        };

        List<NoMansSkyGalaxy> existing = await dbContext.NoMansSkyGalaxies.ToListAsync();
        foreach (NoMansSkyGalaxy galaxy in galaxies)
        {
            if (existing.Any(e => e.Id == galaxy.Id))
            {
                continue;
            }
            dbContext.NoMansSkyGalaxies.Add(galaxy);
        }

        await dbContext.SaveChangesAsync();
    }
}